---
language: ruby

script: bundle exec rake

sudo: false

addons:
  apt:
    packages:
      - libarchive-dev

rvm:
  - jruby

notifications:
  email:
    recipients:
      - development+travis-opener@olery.com

    on_success: change
    on_failure: change

cache: bundler

branches:
  only:
    - master
